"""Corrigindo redefinição da tabela agendamentos

Revision ID: 3fc23ec781b6
Revises: 2081e08bc674
Create Date: 2025-03-20 17:06:09.847436

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fc23ec781b6'
down_revision = '2081e08bc674'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
