"""Corrigindo redefinição da tabela agendamentos

Revision ID: 5595decfd334
Revises: e6cc0d51bccb
Create Date: 2025-03-20 16:59:06.290369

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5595decfd334'
down_revision = 'e6cc0d51bccb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
