"""Corrigindo conflitos na tabela users

Revision ID: 7091a3b0543a
Revises: dc235119ec99
Create Date: 2025-03-20 16:14:35.209852

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7091a3b0543a'
down_revision = 'dc235119ec99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
