"""Corrigindo redefinição da tabela users

Revision ID: 7b4abf97e64f
Revises: ed3701cb87b6
Create Date: 2025-03-20 16:52:46.259216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b4abf97e64f'
down_revision = 'ed3701cb87b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
