"""Adicionando tabelas de Pátio e Câmera

Revision ID: ac4c54b56fbd
Revises: ddb3f74f71d1
Create Date: 2025-03-20 15:06:04.467309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac4c54b56fbd'
down_revision = 'ddb3f74f71d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patios_id'), 'patios', ['id'], unique=False)
    op.create_table('cameras',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('rtmp_url', sa.String(length=255), nullable=False),
    sa.Column('patio_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['patio_id'], ['patios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cameras_id'), 'cameras', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cameras_id'), table_name='cameras')
    op.drop_table('cameras')
    op.drop_index(op.f('ix_patios_id'), table_name='patios')
    op.drop_table('patios')
    # ### end Alembic commands ###
