"""Adicionando campo resultado em Inspecao e relacionamento com Patio

Revision ID: dc235119ec99
Revises: ac4c54b56fbd
Create Date: 2025-03-20 16:04:53.146237

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc235119ec99'
down_revision = 'ac4c54b56fbd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inspecoes', sa.Column('resultado', sa.Text(), nullable=True))
    op.add_column('inspecoes', sa.Column('patio_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'inspecoes', 'patios', ['patio_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'inspecoes', type_='foreignkey')
    op.drop_column('inspecoes', 'patio_id')
    op.drop_column('inspecoes', 'resultado')
    # ### end Alembic commands ###
