"""Criar tabela de inspeções

Revision ID: ddb3f74f71d1
Revises: f195bc1d21f4
Create Date: 2025-03-12 19:22:19.992663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddb3f74f71d1'
down_revision = 'f195bc1d21f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inspecoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_email', sa.String(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('placa', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['usuario_email'], ['users.email'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inspecoes_id'), 'inspecoes', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_inspecoes_id'), table_name='inspecoes')
    op.drop_table('inspecoes')
    # ### end Alembic commands ###
