"""Corrigindo redefinição das tabelas

Revision ID: e6cc0d51bccb
Revises: 7b4abf97e64f
Create Date: 2025-03-20 16:57:47.367481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6cc0d51bccb'
down_revision = '7b4abf97e64f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
