"""Corrigindo conflitos na tabela users

Revision ID: ed3701cb87b6
Revises: 7091a3b0543a
Create Date: 2025-03-20 16:47:08.681192

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed3701cb87b6'
down_revision = '7091a3b0543a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
