"""Corrigir relacionamento User-Agendamento

Revision ID: f195bc1d21f4
Revises: 1becae7a3ce2
Create Date: 2025-03-12 18:12:19.053620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f195bc1d21f4'
down_revision = '1becae7a3ce2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
